version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/" # Location of go.mod
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of the workflow files
    schedule:
      interval: "weekly"